### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by YeYizhou11** [dmelgarm/MudPy#58]
When I set the make_GFs=1,and run the code, there is an errno occur  just like this:
IOError: [Errno 2] No such file or directory: chuxian'/home/boat//cascadia//GFs/dynamic/cascadia.mod_10.8050.sub0001/1.subfault0001.SS.disp.e'

**Comment by Chimon108** [comment]
Hi, Miss Ye, I am having the same problem, is it solved for you?
Traceback (most recent call last):
  File "/home/chimon/Slip_forward/nepal.fwd.py", line 86, in <module>
    stf_falloff_rate=4.0,rupture_name=rupture_name,epicenter=epicenter,time_epi=time_epi)
  File "/home/chimon/MudPy/src/python/mudpy/forward.py", line 310, in waveforms_fakequakes
    G_from_file,G_name)
  File "/home/chimon/MudPy/src/python/mudpy/forward.py", line 1095, in load_fakequakes_synthetics
    Ess+=read(syn_path+staname[ksta]+'.'+nfault+'.SS.'+vord+'.e')
  File "<decorator-gen-31>", line 2, in read
  File "/home/chimon/anaconda2/lib/python2.7/site-packages/obspy/core/util/decorator.py", line 300, in _map_example_filename
    return func(*args, **kwargs)
  File "/home/chimon/anaconda2/lib/python2.7/site-packages/obspy/core/stream.py", line 212, in read
    st = _generic_reader(pathname_or_url, _read, **kwargs)
  File "/home/chimon/anaconda2/lib/python2.7/site-packages/obspy/core/util/base.py", line 700, in _generic_reader
    raise IOError(2, "No such file or directory", pathname)
IOError: [Errno 2] No such file or directory: u'/home/chimon/Slip_forward/Nepal_forward_test/GFs/dynamic/avouac.mod_1.6430.sub0001/KANTP.subfault0001.SS.disp.e'
